################ German language ##################
[de]
languageName = "German"
languageCode = "de-ch"
contentDir = "content/german"
weight = 1

################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
