[[footer]]
name = "Über uns"
url = "about/"
weight = 2
[[footer]]
name = "Projekt"
url = "project/"
weight = 3
[[footer]]
name = "Dienstleistung"
url = "service/"
weight = 4
[[footer]]
name = "Preise"
url = "pricing/"
weight = 5
[[footer]]
name = "Häufige Fragen"
url = "faq/"
weight = 6
[[footer]]
name = "Kontakt"
url = "contact/"
weight = 7
[[main]]
name = "Startseite"
url = ""
weight = 1
[[main]]
name = "Über uns"
url = "about/"
weight = 2
[[main]]
name = "Projekt"
url = "project/"
weight = 3
[[main]]
name = "Blog"
url = "blog/"
weight = 4
[[main]]
hasChildren = true
name = "Mehr"
weight = 5
[[main]]
name = "Dienstleistung"
parent = "Mehr"
url = "service/"
weight = 1
[[main]]
name = "Preise"
parent = "Mehr"
url = "pricing/"
weight = 2
[[main]]
name = "Kontakt"
url = "contact/"
weight = 6
