[[main]]
name = "Über uns"
url = "about/"
weight = 1

[[main]]
name = "Helfer werden"
url = "helfer/"
weight = 2

[[main]]
name = "Spenden"
url = "spenden/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Kontakt"
url = "contact/"
weight = 5



[[footer]]
name = "Über uns"
url = "about/"
weight = 2

[[footer]]
name = "Helfer werden"
url = "helfer/"
weight = 3

[[footer]]
name = "Spenden"
url = "spenden/"
weight = 4

[[footer]]
name = "Blog"
url = "blog/"
weight = 5

[[footer]]
name = "Kontakt"
url = "contact/"
weight = 7