address_descriptors = false
author = "Dominik"
copyright = "Angepasstes Design von [Themefisher](https://themefisher.com/) &  [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "This is meta description"
email = "demo@email.com"
favicon = "images/favicon.png"
google_tag_manager = ""
image = "images/logo.png"
location = "**Igelstation Oberentfelden**  \n5036 Oberentfelden  \nnahe der Tietklinik Aarau West \nasdf\ndd\nddd"
logo = "images/logo.png"
logo_text = "Airspace"
logo_width = "150px"
navbar_fixed = false
phone = "079 740 26 31"
owner = "Danielle Lenzin"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyBbdfu6PjwqvSIrRoMK4Ve3IEz08i5Q2BA"
map_latitude = "47.3481825036509"
map_longitude = "8.049746190256426"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/Igel-retten-100884365735686"
title = "facebook"
# [[social]]
# icon = "fab fa-twitter"
# link = "#"
# title = "twitter"
# [[social]]
# icon = "fab fa-instagram"
# link = "#"
# title = "instagram"
# [[social]]
# icon = "fab fa-github"
# link = "#"
# title = "github"
# [[social]]
# icon = "fab fa-linkedin"
# link = "#"
# title = "linkedin"
