---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: site/content/german/_index.md
  label: Homepage (de)
- type: heading
  label: Blog Post
- type: directory
  path: site/content/german/blog
  label: Post (de)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: site/content/german/author
  label: Author (de)
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Project
- type: directory
  path: site/content/german/project
  label: Project (de)
  create: documents
  match: "**/*"
  templates:
  - project
- type: heading
  label: Other Pages
- type: directory
  path: site/content/german
  label: Other Pages (de)
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: site/content/german
  label: All Pages (de)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: site/config/_default/config.toml
  label: Configuration
- type: document
  path: site/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: site/config/_default/languages.toml
  label: Languages
- type: document
  path: site/config/_default/menus.de.toml
  label: Menu (de)
- type: directory
  path: site/i18n
  label: i18n Translations
  create: all
  match: "**/*"
upload_dir: site/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.87.0
